### PR TITLE
[Agent] Fix kafka inference error

### LINKED ISSUE #520: deepflow collect the clickhose  protocol   as  kafka protocol,which  is messed up
> collect the protocol  as kafka protocol,which is error.

image

image

### PR DESCRIPTION
**Pull request by yuanchaoa**
**Phenomenon and reproduction steps**

**Root cause and solution**

* check payload size and kafka message size

**Impactions**

**Test method**

**Affected branch(es)**

* main

**Checklist**

- [ ] Dependencies update required
- [ ] Common bug (similar problem in other repo)

#### What type of this PR
Examples of user facing changes:
- Features
- Bug fixes
- Docs
- Tests

#### Which issue(s) this PR fixes:
Fixes #520

### CODE REVIEW

File: agent/src/flow_generator/protocol_logs/mq/kafka.rs [hunk 1]
```diff
@@ -88,13 +89,17 @@ impl KafkaLog {
         self.status_code = 0;
     }
 
-    fn request(&mut self, payload: &[u8]) -> Result<AppProtoHead> {
+    fn request(&mut self, payload: &[u8], strict: bool) -> Result<AppProtoHead> {
```
Comment (sharang) [inline agent/src/flow_generator/protocol_logs/mq/kafka.rs:92]: 为什么要有个strict的控制？

Comment (yuanchaoa) [reply agent/src/flow_generator/protocol_logs/mq/kafka.rs:92]: 协议识别的时候严格检查避免误识别，日志解析的时候不用严格检查因为可能有长度截断

Comment (sharang) [reply agent/src/flow_generator/protocol_logs/mq/kafka.rs:92]: 加个注释？中文 + google translate

**Review by sharang — DISMISSED** [review]

**Review by sharang — APPROVED** [review]
