### PR TITLE
[Agent] Fix panic at unreachable code #19895

### LINKED ISSUE #1772: [BUG] agent panic at 'entered unreachable code'
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

deepflow-agent panic, the log output:

```bash
[2022-12-13 18:46:56.028477 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `191`")
[2022-12-13 18:46:56.028575 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `191`")
[2022-12-13 18:46:56.028635 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `224`")
[2022-12-13 18:46:56.028670 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `224`")
[2022-12-13 18:46:56.028790 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `138`")
[2022-12-13 18:46:56.028874 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `194`")
[2022-12-13 18:46:56.029011 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `135`")
[2022-12-13 18:46:56.029093 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `98`")
[2022-12-13 18:46:56.029148 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `173`")
[2022-12-13 18:46:56.029208 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `179`")
[2022-12-13 18:46:56.029286 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `130`")
[2022-12-13 18:46:56.029405 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `157`")
[2022-12-13 18:46:56.029502 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `3`")
[2022-12-13 18:46:56.029566 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `248`")
[2022-12-13 18:46:56.029646 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `3`")
[2022-12-13 18:46:56.029711 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `13`")
[2022-12-13 18:46:56.029786 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `205`")
[2022-12-13 18:46:56.029866 +08:00] WARN [src/dispatcher/local_mode_dispatcher.rs:224] meta_packet update failed: ParsePacketFailed("parse ip_protocol failed: No discriminant in enum `IpProtocol` matches the value `96`")
thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/common/meta_packet.rs:751:25
stack backtrace:
2022-12-13 18:46:56 [eBPF] INFO socket_tracer state is TRACER_INIT, not permit start.
   0: rust_begin_unwind
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: deepflow_agent::common::meta_packet::MetaPacket::update
   4: deepflow_agent::dispatcher::local_mode_dispatcher::LocalModeDispatcher::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### How to reproduce

This happened at 13 nodes of a 58 nodes cluster, deepflow-agent continue panic in a few minutes after restart. 
The other nodes do not appear the  panic.

### DeepFlow version

deepflow-server
```bash
Name: deepflow-server community edition
Branch: v6.1.8
CommitID: 87d23361ecc37fa2d0c9474cce609cbc7abb2de5
RevCount: 7347
Compiler: go version go1.18.9 linux/amd64
CompileTime: 2022-12-13 02:34:01
```
deepflow-agent
```bash
7347-87d23361ecc37fa2d0c9474cce609cbc7abb2de5
Name: deepflow-agent community edition
Branch: v6.1.8
CommitId: 87d23361ecc37fa2d0c9474cce609cbc7abb2de5
RevCount: 7347
Compiler: rustc 1.65.0 (897e37553 2022-11-02)
CompileTime: 2022-12-13 02:34:14
```

### DeepFlow agent list

_No response_

### Kubernetes CNI

cni information:   calico v3.22.1

### Operation-System/Kernel version

os: "Ubuntu 20.04 LTS"
kernel: 5.4.0-121-generic

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yuanchaoa**
### This PR is for:

- Agent

#### Changes to fix the bug
- Delete unreachable code
#### Affected branches
- main
- v6.1
#### Checklist
- [ ] Added unit test to verify the fix.

### CODE REVIEW

File: agent/src/common/meta_packet.rs [hunk 1]
```diff
@@ -747,8 +747,6 @@ impl<'a> MetaPacket<'a> {
                     if let IpAddr::V6(ip) = self.lookup_key.src_ip {
                         self.nd_reply_or_arp_request =
                             self.nd_reply_or_arp_request && !is_unicast_link_local(&ip);
-                    } else {
```
Comment (sharang) [inline agent/src/common/meta_packet.rs:750]: 还需要避免刷 invalid protocol 的日志

**Review by sharang — APPROVED** [review]
